import images from './images';

const collections = [
    {
        number  : '1',
        imgUrl  : images.profile_1,
        title   : 'Anish Agarwal',
        icon    : images.eth4,
        bid     : 'An Embroidiery Artist',
        percen  : 'Maharashtra'
    },
    {
        number  : '2',
        imgUrl  : images.profile_2,
        title   : 'Sayak Sen',
        icon    : images.eth4,
        bid     : 'Famous Sweet Maker',
        percen  : 'West Bengal'
    },
    {
        number  : '3',
        imgUrl  : images.profile_3,
        title   : 'Ankit Kumar',
        icon    : images.eth4,
        bid     : 'Village Potter',
        percen  : 'Bihar'
    },
    {
        number  : '4',
        imgUrl  : images.profile_4,
        title   : 'Srijita Jana',
        icon    : images.eth4,
        bid     : 'Ornament Designer',
        percen  : 'Gujrat'
    },
    {
        number  : '5',
        imgUrl  : images.profile_5,
        title   : 'Priyanshu Priya',
        icon    : images.eth4,
        bid     : 'Baked Sweets',
        percen  : 'Assam'
    },
]

const featureds = [
    {
        imgUrl  : images.gradient_1,
        imgUrl2 : images.gradient_5,
        imgUrl3 : images.gradient_4,
        imgUrl4 : images.gradient_2,
        title   : 'Jewellery',
        profil  : images.profile_6,
        names    : 'by Mohini Kumari',
        item    : 'Total 54 items',
    },
    {
        imgUrl  : images.gradient_4,
        imgUrl2 : images.gradient_1,
        imgUrl3 : images.gradient_7,
        imgUrl4 : images.gradient_6,
        title   : 'Home Decor',
        profil  : images.profile_7,
        names    : 'by Arief Wahyudi',
        item    : 'Total 54 items',
    },
    {
        imgUrl  : images.gradient_6,
        imgUrl2 : images.gradient_2,
        imgUrl3 : images.gradient_5,
        imgUrl4 : images.gradient_6,
        title   : 'Ethnics',
        profil  : images.profile_8,
        names   : 'by Arkhani',
        item    : 'Total 54 items',
    },
] 
const discovers = [
    {
        imgUrl   : images.gradient_1,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'Glass Bangles',
        icon     : images.eth2,
        bid      : '15 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_2,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'Rajasthani Lehenga',
        icon     : images.eth2,
        bid      : '120 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_3,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'Joynagar Moya',
        icon     : images.eth2,
        bid      : '8 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_4,
        profil_1 : images.profile_6,
        profil_2 : images.profile_7,
        profil_3 : images.profile_8,
        profil_4 : images.profile_4,
        title    : 'Diwali Diyas',
        icon     : images.eth2,
        bid      : '5 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_5,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'Shantiniketan Art',
        icon     : images.eth2,
        bid      : '23 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_6,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'Gujrati Kurti',
        icon     : images.eth2,
        bid      : '12 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_7,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'Teracotta Artworks',
        icon     : images.eth2,
        bid      : '15 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_8,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'Wedding Necklace',
        icon     : images.eth2,
        bid      : '20 USDT',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },

]

export default { collections, featureds,discovers };